#ifndef SMARTPIANO_VERSION_H_
#define SMARTPIANO_VERSION_H_

#define SMARTPIANO_MAJOR_VERSION 0
#define SMARTPIANO_MINOR_VERSION 1
#define SMARTPIANO_PATCH_VERSION 0
#define SMARTPIANO_VERSION_STRING "v0.1.0"

#endif  // SMARTPIANO_VERSION_H_